# Generated by Django 5.0 on 2023-12-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idea',
        ),
    ]
