# Generated by Django 5.0 on 2023-12-19 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0004_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Tech',
        ),
        migrations.RenameField(
            model_name='tech',
            old_name='course',
            new_name='Tech',
        ),
    ]
