# Generated by Django 5.0 on 2023-12-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0005_rename_technology_tech_rename_course_tech_tech'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Syllabus', models.CharField(max_length=255)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_type', models.CharField(choices=[('main_project', 'Main Project'), ('mini_project', 'Mini Project'), ('class_project', 'Class Project')], max_length=100)),
                ('Title_of_theproject', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_app.course')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_app.tech')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_app.syllabus')),
            ],
        ),
    ]
